"""Add responses

Revision ID: d6f523500dc1
Revises: 8938b4f74e04
Create Date: 2026-09-05 19:33:31.152047

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6f523500dc1"
down_revision: str | Sequence[str] | None = "8938b4f74e04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "responses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("listing_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.Column(
            "status", sa.Enum("REJECTED", "ACCEPTED", "NEW", name="response_status"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["listing_id"], ["listings.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("listing_id", "author_id", name="uq_response_per_user"),
    )
    op.create_index(op.f("ix_responses_author_id"), "responses", ["author_id"], unique=False)
    op.create_index(op.f("ix_responses_listing_id"), "responses", ["listing_id"], unique=False)
    op.create_index(
        "ix_responses_listing_status", "responses", ["listing_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_responses_listing_status", table_name="responses")
    op.drop_index(op.f("ix_responses_listing_id"), table_name="responses")
    op.drop_index(op.f("ix_responses_author_id"), table_name="responses")
    op.drop_table("responses")
    sa.Enum(name="response_status").drop(op.get_bind(), checkfirst=True)

    # ### end Alembic commands ###
