"""Add user locale

Revision ID: 1d327b29c99e
Revises: 293e027e5b2f
Create Date: 2026-09-20 11:56:52.264895

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1d327b29c99e"
down_revision: str | Sequence[str] | None = "293e027e5b2f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("locale", sa.String(length=5), server_default="en", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "locale")
    # ### end Alembic commands ###
