"""Add embeddings to photos

Revision ID: 44343e7a5b68
Revises: 38cd2065459a
Create Date: 2026-09-14 14:54:24.868709

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "44343e7a5b68"
down_revision: str | Sequence[str] | None = "38cd2065459a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_listings_location"), "listings", ["location"], unique=False)
    op.add_column(
        "photos", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True)
    )
    op.add_column("photos", sa.Column("bbox", sa.JSON(), nullable=True))
    op.add_column("photos", sa.Column("dog_detected", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("photos", "dog_detected")
    op.drop_column("photos", "bbox")
    op.drop_column("photos", "embedding")
    op.drop_index(op.f("ix_listings_location"), table_name="listings")
    # ### end Alembic commands ###
