"""Add users and listings

Revision ID: 966e0c4d5e48
Revises: d26412c7c186
Create Date: 2026-09-03 13:22:33.587616

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "966e0c4d5e48"
down_revision: str | Sequence[str] | None = "d26412c7c186"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "listings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.Enum("LOST", "FOUND", name="listing_kind"), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "RESOLVED", "ARCHIVED", name="listing_status"),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("happened_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("breed", sa.String(length=50), nullable=True),
        sa.Column("color", sa.String(length=60), nullable=True),
        sa.Column("sex", sa.Enum("UNKNOWN", "MALE", "FEMALE", name="dog_sex"), nullable=False),
        sa.Column("size", sa.Enum("SMALL", "MEDIUM", "LARGE", name="dog_size"), nullable=True),
        sa.Column("size_note", sa.String(length=120), nullable=True),
        sa.Column("contact_phone", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_listings_feed", "listings", ["kind", "status", "happened_at"], unique=False)
    op.create_index(op.f("ix_listings_owner_id"), "listings", ["owner_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_listings_owner_id"), table_name="listings")
    op.drop_index("ix_listings_feed", table_name="listings")
    op.drop_table("listings")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")

    bind = op.get_bind()
    sa.Enum(name="listing_kind").drop(bind, checkfirst=True)
    sa.Enum(name="listing_status").drop(bind, checkfirst=True)
    sa.Enum(name="dog_sex").drop(bind, checkfirst=True)
    sa.Enum(name="dog_size").drop(bind, checkfirst=True)
    # ### end Alembic commands ###
